name: ci
on:
   push:
      branches: master
jobs:
   build-and-deploy:
      runs-on: ubuntu-latest
      name: "Build to ACR"
      steps:
         - uses: actions/checkout@main
         - uses: azure/login@v1
           with:
              creds: ${{ secrets.AZURE_CREDENTIALS }}
         - uses: azure/docker-login@v1
           with:
              login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
              username: ${{ secrets.REGISTRY_USERNAME }}
              password: ${{ secrets.REGISTRY_PASSWORD }}
         - run: |
            export REPO=$(echo $GITHUB_REPOSITORY|awk '{n=split($0,e,"/");print e[n]}')
            export CONTAINER_NAME=${{ secrets.REGISTRY_LOGIN_SERVER }}/$REPO
            docker build . -t $CONTAINER_NAME:latest
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/$REPO:latest
